"use server";
import {revalidatePath} from "next/cache";
import {requireAdmin} from "../../lib/portal-auth";
export type ClientState={error?:string;message?:string;fields?:Record<string,string>};
const statuses=["prospect","onboarding","active","paused","completed","archived"];
function values(formData:FormData){return{business_name:String(formData.get("business_name")??"").trim(),primary_contact_name:String(formData.get("primary_contact_name")??"").trim(),primary_contact_email:String(formData.get("primary_contact_email")??"").trim(),phone:String(formData.get("phone")??"").trim(),website:String(formData.get("website")??"").trim(),status:String(formData.get("status")??"active")}}
function validate(fields:ReturnType<typeof values>){if(fields.business_name.length<2)return"Business name must be at least two characters.";if(fields.primary_contact_email&&!/^\S+@\S+\.\S+$/.test(fields.primary_contact_email))return"Enter a valid contact email.";if(!statuses.includes(fields.status))return"Choose a valid status.";if(fields.website){try{new URL(fields.website)}catch{return"Website must be a complete URL."}}}
export async function saveClient(_:ClientState,formData:FormData):Promise<ClientState>{const{supabase}=await requireAdmin();const fields=values(formData);const invalid=validate(fields);if(invalid)return{error:invalid,fields};const id=String(formData.get("id")??"");const payload={...fields,primary_contact_name:fields.primary_contact_name||null,primary_contact_email:fields.primary_contact_email||null,phone:fields.phone||null,website:fields.website||null};const result=id?await supabase.from("clients").update(payload).eq("id",id).select("id").single():await supabase.from("clients").insert(payload).select("id").single();if(result.error){console.error("Client save failed",{message:result.error.message,code:result.error.code,details:result.error.details,hint:result.error.hint});return{error:"The client could not be saved.",fields}}revalidatePath("/portal/clients");revalidatePath(`/portal/clients/${result.data.id}`);return{message:id?"Client updated.":"Client created."}}
export async function addMembership(_:ClientState,formData:FormData):Promise<ClientState>{const{supabase}=await requireAdmin();const clientId=String(formData.get("clientId")??"");const userId=String(formData.get("userId")??"");if(!clientId||!userId)return{error:"Choose an authenticated user."};const{error}=await supabase.from("client_memberships").insert({client_id:clientId,user_id:userId});if(error){console.error("Membership add failed",{message:error.message,code:error.code,details:error.details,hint:error.hint});return{error:error.code==="23505"?"That user already belongs to this client.":"The membership could not be added."}}revalidatePath(`/portal/clients/${clientId}`);return{message:"Membership added."}}
export async function removeMembership(formData:FormData){const{supabase}=await requireAdmin();const id=String(formData.get("id")??"");const clientId=String(formData.get("clientId")??"");const{error}=await supabase.from("client_memberships").delete().eq("id",id);if(error)console.error("Membership removal failed",{message:error.message,code:error.code,details:error.details,hint:error.hint});revalidatePath(`/portal/clients/${clientId}`)}
