"use client";
import {useActionState} from "react";
import {addMembership,saveClient,type ClientState} from "./actions";
const input="rounded-xl border border-[#E7DCC1]/10 bg-[#382F24] p-3";
export const clientStatuses=["prospect","onboarding","active","paused","completed","archived"];
type ClientValues={id?:string;business_name?:string;primary_contact_name?:string|null;primary_contact_email?:string|null;phone?:string|null;website?:string|null;status?:string};
export function ClientForm({client}:{client?:ClientValues}){const[state,action,pending]=useActionState(saveClient,{} as ClientState);const value=(key:keyof ClientValues)=>state.fields?.[key]??String(client?.[key]??"");return <form action={action} className="grid gap-4 rounded-[2rem] border border-[#E7DCC1]/10 bg-[#211C16] p-7">{client?.id&&<input type="hidden" name="id" value={client.id}/>}<label>Business name<input className={`${input} mt-2 w-full`} name="business_name" required minLength={2} defaultValue={value("business_name")}/></label><div className="grid gap-4 sm:grid-cols-2"><label>Primary contact<input className={`${input} mt-2 w-full`} name="primary_contact_name" defaultValue={value("primary_contact_name")}/></label><label>Contact email<input className={`${input} mt-2 w-full`} name="primary_contact_email" type="email" defaultValue={value("primary_contact_email")}/></label><label>Phone<input className={`${input} mt-2 w-full`} name="phone" defaultValue={value("phone")}/></label><label>Website<input className={`${input} mt-2 w-full`} name="website" type="url" defaultValue={value("website")}/></label></div><label>Status<select className={`${input} mt-2 w-full`} name="status" defaultValue={value("status")||"active"}>{clientStatuses.map(s=><option key={s}>{s}</option>)}</select></label><Notice state={state}/><button disabled={pending} className="rounded-full bg-[#C6A972] px-5 py-3 text-xs font-semibold uppercase tracking-[.18em] text-[#17130E] disabled:opacity-50">{pending?"Saving…":client?.id?"Save client":"Add client"}</button></form>}
export function MembershipForm({clientId,profiles}:{clientId:string;profiles:{id:string;label:string}[]}){const[state,action,pending]=useActionState(addMembership,{} as ClientState);return <form action={action} className="mt-6 grid gap-3 sm:grid-cols-[1fr_auto]"><input type="hidden" name="clientId" value={clientId}/><select name="userId" required className={input}><option value="">Add an authenticated user…</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select><button disabled={pending} className="rounded-full border border-[#C6A972]/40 px-5 py-3 text-xs text-[#C6A972]">{pending?"Adding…":"Add member"}</button><Notice state={state}/></form>}
function Notice({state}:{state:ClientState}){return <div className="sm:col-span-2">{state.error&&<p role="alert" className="text-sm text-red-200">{state.error}</p>}{state.message&&<p role="status" className="text-sm text-[#C6A972]">{state.message}</p>}</div>}
