"use server";
import { revalidatePath } from "next/cache";
import { requirePortalUser } from "../../lib/portal-auth";
import { requireAdmin } from "../../lib/portal-auth";

export type RequestState={error?:string;message?:string};
export async function createRequest(_:RequestState,formData:FormData):Promise<RequestState>{const {supabase,profile}=await requirePortalUser();const title=String(formData.get("title")??"").trim();const description=String(formData.get("description")??"").trim();const projectId=String(formData.get("projectId")??"");const clientId=String(formData.get("clientId")??"");const priority=String(formData.get("priority")??"normal");if(title.length<3||description.length<10||!clientId||!projectId)return{error:"Add a title, description, client, and project."};if(!["normal","high","urgent"].includes(priority))return{error:"Choose a valid priority."};const {error}=await supabase.from("change_requests").insert({client_id:clientId,project_id:projectId,title,description,priority,status:"submitted",submitted_by:profile.id});if(error){console.error("Request submission failed",{message:error.message,code:error.code,details:error.details,hint:error.hint});return{error:"The request could not be submitted. Check your access and try again."}}revalidatePath("/portal");revalidatePath("/portal/requests");return{message:"Request submitted."}}
export async function addComment(_:RequestState,formData:FormData):Promise<RequestState>{const {supabase,profile}=await requirePortalUser();const requestId=String(formData.get("requestId")??"");const body=String(formData.get("body")??"").trim();if(!requestId||body.length<1)return{error:"Write a comment first."};if(body.length>4000)return{error:"Comments must be 4,000 characters or fewer."};const {error}=await supabase.from("change_request_comments").insert({request_id:requestId,author_user_id:profile.id,body,is_internal:false});if(error){console.error("Request comment failed",{message:error.message,code:error.code,details:error.details,hint:error.hint});return{error:"Your reply could not be saved."}}revalidatePath(`/portal/requests/${requestId}`);return{message:"Reply added."}}
export async function addAdminComment(_:RequestState,formData:FormData):Promise<RequestState>{const{supabase,profile}=await requireAdmin();const requestId=String(formData.get("requestId")??"");const body=String(formData.get("body")??"").trim();const internal=formData.get("internal")==="on";if(!requestId||!body||body.length>4000)return{error:"Enter a comment of 4,000 characters or fewer."};const{error}=await supabase.from("change_request_comments").insert({request_id:requestId,author_user_id:profile.id,body,is_internal:internal});if(error){console.error("Admin comment failed",error);return{error:"The comment could not be saved."}}revalidatePath(`/portal/requests/${requestId}`);return{message:internal?"Internal comment added.":"Client reply added."}}
export async function updateRequest(_:RequestState,formData:FormData):Promise<RequestState>{const{supabase}=await requireAdmin();const id=String(formData.get("id")??"");const status=String(formData.get("status")??"");const adminNotes=String(formData.get("admin_notes")??"").trim();const statuses=["submitted","reviewing","scheduled","in_progress","awaiting_client","completed","declined"];if(!id||!statuses.includes(status))return{error:"Choose a valid request status."};const{error}=await supabase.from("change_requests").update({status,admin_notes:adminNotes||null}).eq("id",id);if(error){console.error("Request update failed",{message:error.message,code:error.code,details:error.details,hint:error.hint});return{error:"The request could not be updated."}}revalidatePath("/portal/requests");revalidatePath(`/portal/requests/${id}`);return{message:"Request updated."}}
