import Link from "next/link";
import { requirePortalUser } from "../lib/portal-auth";
export default async function PortalPage(){
 const {supabase,profile}=await requirePortalUser();
 const [{data:projects},{data:files},{data:activity}]=await Promise.all([
  supabase.from("projects").select("id,name,status,description,due_date").order("updated_at",{ascending:false}),
  supabase.from("files").select("id,display_name,size_bytes,updated_at,project_id").order("updated_at",{ascending:false}).limit(6),
  supabase.from("activity_log").select("id,action,created_at,project_id").order("created_at",{ascending:false}).limit(6)
 ]);
 const bytes=(files??[]).reduce((n,f)=>n+Number(f.size_bytes),0);
 return <div className="mx-auto max-w-[90rem] px-6 py-16 lg:px-12"><div className="section-label">Client workspace</div><h1 className="mt-5 text-[clamp(3.5rem,7vw,7rem)] font-semibold leading-[.86] tracking-[-.07em]">Welcome back, {profile.full_name.split(" ")[0]||"there"}.</h1><div className="mt-14 grid gap-4 md:grid-cols-3"><Metric label="Active projects" value={String((projects??[]).filter(p=>p.status!=="COMPLETE").length)}/><Metric label="Shared files" value={String(files?.length??0)}/><Metric label="Storage in view" value={`${(bytes/1048576).toFixed(1)} MB`}/></div><section className="mt-20"><div className="flex items-end justify-between"><div><div className="section-label">Active projects</div><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em]">The work in motion.</h2></div></div><div className="mt-9 grid gap-4 lg:grid-cols-2">{projects?.length?projects.map(p=><Link key={p.id} href={`/portal/projects/${p.id}`} className="group rounded-[1.75rem] border border-[#E7DCC1]/10 bg-[#292219] p-8 hover:border-[#C6A972]/30"><span className="text-[10px] uppercase tracking-[.2em] text-[#C6A972]">{p.status.replace("_"," ")}</span><h3 className="mt-12 text-3xl font-semibold tracking-[-.04em]">{p.name}</h3><p className="mt-4 text-sm leading-7 text-[#E7DCC1]/55">{p.description||"Project workspace and shared deliverables."}</p></Link>):<Empty text="No projects have been assigned yet." />}</div></section><div className="mt-20 grid gap-12 lg:grid-cols-2"><List title="Recent files" rows={(files??[]).map(f=>f.display_name)}/><List title="Recent activity" rows={(activity??[]).map(a=>a.action)}/></div><section className="mt-20 rounded-[2rem] border border-[#E7DCC1]/10 bg-[#211C16] p-8"><div className="section-label">Upcoming meetings</div><p className="mt-5 text-[#E7DCC1]/55">Scheduled meetings will appear here when calendar synchronization is enabled.</p><a href="https://cal.com/kuikengroup/initial-conversation" target="_blank" rel="noreferrer" className="mt-7 inline-block text-sm text-[#C6A972]">Schedule a conversation →</a></section></div>
}
function Metric({label,value}:{label:string,value:string}){return <div className="rounded-2xl border border-[#E7DCC1]/10 bg-[#211C16] p-6"><div className="text-4xl font-semibold">{value}</div><div className="mt-3 text-[10px] uppercase tracking-[.2em] text-[#E7DCC1]/45">{label}</div></div>}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed border-[#E7DCC1]/15 p-10 text-sm text-[#E7DCC1]/50">{text}</div>}
function List({title,rows}:{title:string,rows:string[]}){return <section><div className="section-label">{title}</div><div className="mt-5 border-t border-[#E7DCC1]/10">{rows.length?rows.map((r,i)=><div key={`${r}-${i}`} className="border-b border-[#E7DCC1]/10 py-4 text-sm text-[#E7DCC1]/65">{r}</div>):<p className="py-6 text-sm text-[#E7DCC1]/45">Nothing here yet.</p>}</div></section>}
